import React,{useReducer} from 'react';
import SongsContext from './songsContext';
import SongsReducer from './songsReducer';

const SongsState = props => {
    const initialState = {
        recent: {
            items: [
                {
                    track: {
                        href: "https://api.spotify.com/v1/tracks/2gNfxysfBRfl9Lvi9T3v6R",
                        id: "2gNfxysfBRfl9Lvi9T3v6R",
                        name: "Disciples",
                        image: "https://i.scdn.co/image/966ade7a8c43b72faa53822b74a899c675aaafee",
                    },
                },
                {
                    track: {
                        href: "https://api.spotify.com/v1/tracks/2X485T9Z5Ly0xyaghN73ed",
                        id: "2X485T9Z5Ly0xyaghN73ed",
                        name: "Let It Happen",
                        image: "https://i.scdn.co/image/966ade7a8c43b72faa53822b74a899c675aaafee",
                    },
                },
                {
                    track: {
                        href: "https://api.spotify.com/v1/tracks/2X485T9Z5Ly0xyaghN73ed",
                        id: "2X485T9Z5Ly0xyaghN73ed",
                        name: "Let It Happen",
                        image: "https://i.scdn.co/image/966ade7a8c43b72faa53822b74a899c675aaafee",
                    },
                },
                {
                    track: {
                        href: "https://api.spotify.com/v1/tracks/2gNfxysfBRfl9Lvi9T3v6R",
                        id: "2gNfxysfBRfl9Lvi9T3v6R",
                        name: "Disciples",
                        image: "https://i.scdn.co/image/966ade7a8c43b72faa53822b74a899c675aaafee",
                    },
                },
            ],
        },
        current: {
            "album": {
                "album_type": "album",
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/2jHp7gQArCQrlMvdrIVFCg"
                        },
                        "href": "https://api.spotify.com/v1/artists/2jHp7gQArCQrlMvdrIVFCg",
                        "id": "2jHp7gQArCQrlMvdrIVFCg",
                        "name": "Anson Seabra",
                        "type": "artist",
                        "uri": "spotify:artist:2jHp7gQArCQrlMvdrIVFCg"
                    }
                ],
                "available_markets": [
                    "AD",
                    "AE",
                    "AG",
                    "AL",
                    "AM",
                    "AO",
                    "AR",
                    "AT",
                    "AU",
                    "AZ",
                    "BA",
                    "BB",
                    "BD",
                    "BE",
                    "BF",
                    "BG",
                    "BH",
                    "BI",
                    "BJ",
                    "BN",
                    "BO",
                    "BR",
                    "BS",
                    "BT",
                    "BW",
                    "BY",
                    "BZ",
                    "CA",
                    "CH",
                    "CI",
                    "CL",
                    "CM",
                    "CO",
                    "CR",
                    "CV",
                    "CW",
                    "CY",
                    "CZ",
                    "DE",
                    "DJ",
                    "DK",
                    "DM",
                    "DO",
                    "DZ",
                    "EC",
                    "EE",
                    "EG",
                    "ES",
                    "FI",
                    "FJ",
                    "FM",
                    "FR",
                    "GA",
                    "GB",
                    "GD",
                    "GE",
                    "GH",
                    "GM",
                    "GN",
                    "GQ",
                    "GR",
                    "GT",
                    "GW",
                    "GY",
                    "HK",
                    "HN",
                    "HR",
                    "HT",
                    "HU",
                    "ID",
                    "IE",
                    "IL",
                    "IN",
                    "IS",
                    "IT",
                    "JM",
                    "JO",
                    "JP",
                    "KE",
                    "KG",
                    "KH",
                    "KI",
                    "KM",
                    "KN",
                    "KR",
                    "KW",
                    "KZ",
                    "LA",
                    "LB",
                    "LC",
                    "LI",
                    "LK",
                    "LR",
                    "LS",
                    "LT",
                    "LU",
                    "LV",
                    "MA",
                    "MC",
                    "MD",
                    "ME",
                    "MG",
                    "MH",
                    "MK",
                    "ML",
                    "MN",
                    "MO",
                    "MR",
                    "MT",
                    "MU",
                    "MV",
                    "MW",
                    "MX",
                    "MY",
                    "MZ",
                    "NA",
                    "NE",
                    "NG",
                    "NI",
                    "NL",
                    "NO",
                    "NP",
                    "NR",
                    "NZ",
                    "OM",
                    "PA",
                    "PE",
                    "PG",
                    "PH",
                    "PK",
                    "PL",
                    "PS",
                    "PT",
                    "PW",
                    "PY",
                    "QA",
                    "RO",
                    "RS",
                    "RU",
                    "RW",
                    "SA",
                    "SB",
                    "SC",
                    "SE",
                    "SG",
                    "SI",
                    "SK",
                    "SL",
                    "SM",
                    "SN",
                    "SR",
                    "ST",
                    "SV",
                    "SZ",
                    "TD",
                    "TG",
                    "TH",
                    "TL",
                    "TN",
                    "TO",
                    "TR",
                    "TT",
                    "TV",
                    "TW",
                    "TZ",
                    "UA",
                    "UG",
                    "US",
                    "UY",
                    "UZ",
                    "VC",
                    "VN",
                    "VU",
                    "WS",
                    "XK",
                    "ZA",
                    "ZM",
                    "ZW"
                ],
                "external_urls": {
                    "spotify": "https://open.spotify.com/album/46NEhlXaMzNTg19kSBthTv"
                },
                "href": "https://api.spotify.com/v1/albums/46NEhlXaMzNTg19kSBthTv",
                "id": "46NEhlXaMzNTg19kSBthTv",
                "images": [
                    {
                        "height": 640,
                        "url": "https://i.scdn.co/image/ab67616d0000b273e471b0b396a4dc0c0066d4f1",
                        "width": 640
                    },
                    {
                        "height": 300,
                        "url": "https://i.scdn.co/image/ab67616d00001e02e471b0b396a4dc0c0066d4f1",
                        "width": 300
                    },
                    {
                        "height": 64,
                        "url": "https://i.scdn.co/image/ab67616d00004851e471b0b396a4dc0c0066d4f1",
                        "width": 64
                    }
                ],
                "name": "Songs I Wrote in My Bedroom",
                "release_date": "2020-05-08",
                "release_date_precision": "day",
                "total_tracks": 15,
                "type": "album",
                "uri": "spotify:album:46NEhlXaMzNTg19kSBthTv"
            },
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/2jHp7gQArCQrlMvdrIVFCg"
                    },
                    "href": "https://api.spotify.com/v1/artists/2jHp7gQArCQrlMvdrIVFCg",
                    "id": "2jHp7gQArCQrlMvdrIVFCg",
                    "name": "Anson Seabra",
                    "type": "artist",
                    "uri": "spotify:artist:2jHp7gQArCQrlMvdrIVFCg"
                }
            ],
            "available_markets": [
                "AD",
                "AE",
                "AG",
                "AL",
                "AM",
                "AO",
                "AR",
                "AT",
                "AU",
                "AZ",
                "BA",
                "BB",
                "BD",
                "BE",
                "BF",
                "BG",
                "BH",
                "BI",
                "BJ",
                "BN",
                "BO",
                "BR",
                "BS",
                "BT",
                "BW",
                "BY",
                "BZ",
                "CA",
                "CH",
                "CI",
                "CL",
                "CM",
                "CO",
                "CR",
                "CV",
                "CW",
                "CY",
                "CZ",
                "DE",
                "DJ",
                "DK",
                "DM",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FJ",
                "FM",
                "FR",
                "GA",
                "GB",
                "GD",
                "GE",
                "GH",
                "GM",
                "GN",
                "GQ",
                "GR",
                "GT",
                "GW",
                "GY",
                "HK",
                "HN",
                "HR",
                "HT",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JM",
                "JO",
                "JP",
                "KE",
                "KG",
                "KH",
                "KI",
                "KM",
                "KN",
                "KR",
                "KW",
                "KZ",
                "LA",
                "LB",
                "LC",
                "LI",
                "LK",
                "LR",
                "LS",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MD",
                "ME",
                "MG",
                "MH",
                "MK",
                "ML",
                "MN",
                "MO",
                "MR",
                "MT",
                "MU",
                "MV",
                "MW",
                "MX",
                "MY",
                "MZ",
                "NA",
                "NE",
                "NG",
                "NI",
                "NL",
                "NO",
                "NP",
                "NR",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PG",
                "PH",
                "PK",
                "PL",
                "PS",
                "PT",
                "PW",
                "PY",
                "QA",
                "RO",
                "RS",
                "RU",
                "RW",
                "SA",
                "SB",
                "SC",
                "SE",
                "SG",
                "SI",
                "SK",
                "SL",
                "SM",
                "SN",
                "SR",
                "ST",
                "SV",
                "SZ",
                "TD",
                "TG",
                "TH",
                "TL",
                "TN",
                "TO",
                "TR",
                "TT",
                "TV",
                "TW",
                "TZ",
                "UA",
                "UG",
                "US",
                "UY",
                "UZ",
                "VC",
                "VN",
                "VU",
                "WS",
                "XK",
                "ZA",
                "ZM",
                "ZW"
            ],
            "disc_number": 1,
            "duration_ms": 257454,
            "explicit": false,
            "external_ids": {
                "isrc": "TCAET2083115"
            },
            "external_urls": {
                "spotify": "https://open.spotify.com/track/2oG04ocya1vI7rnijoNH7i"
            },
            "href": "https://api.spotify.com/v1/tracks/2oG04ocya1vI7rnijoNH7i",
            "id": "2oG04ocya1vI7rnijoNH7i",
            "is_local": false,
            "name": "Dawning of Spring",
            "popularity": 47,
            "preview_url": "https://p.scdn.co/mp3-preview/1bd4fd9b68f16e2fb002890b752f0f44bb4ff6f8?cid=774b29d4f13844c495f206cafdad9c86",
            "track_number": 1,
            "type": "track",
            "uri": "spotify:track:2oG04ocya1vI7rnijoNH7i"
        }
    };

    const [state, dispatch] = useReducer(SongsReducer, initialState);


    return(<SongsContext.Provider value={{current:state.current}} >
        {props.children}
    </SongsContext.Provider>)
}

export default SongsState;